[build]
  command = "npm run build || exit 0"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/login"
  to = "/login"
  status = 200
  force = true
  conditions = {Role = ["!admin"]}

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = true
  conditions = {Role = ["admin"]} 