[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@libsql/client"]

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"