[build]
  command = "npm run build"
  publish = ".netlify/functions-internal"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login"
  status = 200
  force = true
  conditions = {Role = ["!admin"]}

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@libsql/client"] 